address = "127.0.0.1"
manage_port = 10000

[users]

[users.me]
hash = ""
passwd = "Hvxlyctdytxxfg"
nick = "me"
status = ""
upload_traffic = ""
download_traffic = ""
traffic_total = ""
[users.to]
hash = ""
passwd = "test"
nick = "test"
status = ""
upload_traffic = ""
download_traffic = ""
traffic_total = ""
