address = "127.0.0.1"
manage_port = 10000

[users]

[users.me]
hash = "1d6501dd05789331c94a765b0e1e2682d95ec06d8fd4c91703214b44"
passwd = "Hvxlyctdytxxfg"
nick = "me"
status = ""
upload_traffic = ""
download_traffic = ""
traffic_total = ""
[users.to]
hash = "36417c02cab12df31a6c93c74b80a8bf485f90098c1b2ddb1a35367a"
passwd = "test"
nick = "test"
status = ""
upload_traffic = ""
download_traffic = ""
traffic_total = ""

[users.three]
hash = "0e96722be6e675d749640634b35d0c6e6e7ee22232e927676afc2837"
passwd = "test"
nick = "test"
status = ""
upload_traffic = ""
download_traffic = ""
traffic_total = ""
